"""3D/AR Agent -- 3D model creation, scene generation, AR content."""
from __future__ import annotations
import logging, json, math
from typing import Any
from pathlib import Path
from vera.brain.agents.base import BaseAgent, Tool
from vera.providers.models import ModelTier
logger = logging.getLogger(__name__)

class Generate3DModelTool(Tool):
    def __init__(self): super().__init__(name="generate_3d_model",description="Generate basic 3D models (cube, sphere, cylinder, etc)",parameters={"shape":{"type":"str","description":"cube|sphere|cylinder|cone|torus|plane"},"size":{"type":"float","description":"Size/radius"},"color":{"type":"str","description":"Color hex"},"output":{"type":"str","description":"Output .obj path"}})
    async def execute(self, **kw: Any) -> dict[str, Any]:
        shape=kw.get("shape","cube"); size=kw.get("size",1.0); out=kw.get("output",f"{shape}.obj")
        try:
            vertices=[]; faces=[]
            if shape=="cube":
                s=size/2
                vertices=[(-s,-s,-s),(s,-s,-s),(s,s,-s),(-s,s,-s),(-s,-s,s),(s,-s,s),(s,s,s),(-s,s,s)]
                faces=[(1,2,3,4),(5,8,7,6),(1,5,6,2),(2,6,7,3),(3,7,8,4),(5,1,4,8)]
            elif shape=="plane":
                s=size/2; vertices=[(-s,0,-s),(s,0,-s),(s,0,s),(-s,0,s)]; faces=[(1,2,3,4)]
            else:
                # Generate sphere-like mesh
                segments=16; rings=8
                for i in range(rings+1):
                    phi=math.pi*i/rings
                    for j in range(segments):
                        theta=2*math.pi*j/segments
                        x=size*math.sin(phi)*math.cos(theta); y=size*math.cos(phi); z=size*math.sin(phi)*math.sin(theta)
                        vertices.append((x,y,z))
                for i in range(rings):
                    for j in range(segments):
                        a=i*segments+j+1; b=i*segments+(j+1)%segments+1; c=(i+1)*segments+(j+1)%segments+1; d=(i+1)*segments+j+1
                        faces.append((a,b,c,d))
            with open(out,"w") as f:
                f.write(f"# Generated by eVera 3D Agent\n# Shape: {shape}\n")
                for v in vertices: f.write(f"v {v[0]:.4f} {v[1]:.4f} {v[2]:.4f}\n")
                for face in faces: f.write("f "+" ".join(str(v) for v in face)+"\n")
            return {"status":"success","shape":shape,"output":out,"vertices":len(vertices),"faces":len(faces)}
        except Exception as e: return {"status":"error","message":str(e)}

class SceneBuilderTool(Tool):
    def __init__(self): super().__init__(name="scene_builder",description="Build 3D scene from objects",parameters={"scene_name":{"type":"str","description":"Scene name"},"objects":{"type":"str","description":"JSON array [{shape,position,size,color}]"},"output":{"type":"str","description":"Output scene file path"}})
    async def execute(self, **kw: Any) -> dict[str, Any]:
        try:
            objects=json.loads(kw.get("objects","[]")) if isinstance(kw.get("objects"),str) else kw.get("objects",[])
            scene={"name":kw.get("scene_name","scene"),"objects":objects,"camera":{"position":[0,5,10],"target":[0,0,0]},"lights":[{"type":"ambient","intensity":0.5},{"type":"directional","position":[5,10,5],"intensity":0.8}]}
            out=kw.get("output","scene.json"); Path(out).write_text(json.dumps(scene,indent=2))
            return {"status":"success","scene":kw.get("scene_name",""),"objects":len(objects),"output":out}
        except Exception as e: return {"status":"error","message":str(e)}

class ModelConverterTool(Tool):
    def __init__(self): super().__init__(name="model_converter",description="Convert between 3D formats (OBJ, STL, PLY)",parameters={"input":{"type":"str","description":"Input model path"},"output":{"type":"str","description":"Output path (.obj/.stl/.ply)"}})
    async def execute(self, **kw: Any) -> dict[str, Any]:
        try:
            import trimesh; mesh=trimesh.load(kw["input"]); mesh.export(kw["output"])
            return {"status":"success","input":kw["input"],"output":kw["output"],"vertices":len(mesh.vertices),"faces":len(mesh.faces)}
        except ImportError: return {"status":"error","message":"pip install trimesh"}
        except Exception as e: return {"status":"error","message":str(e)}

class ModelInfoTool(Tool):
    def __init__(self): super().__init__(name="model_info",description="Get 3D model info (vertices, faces, bounds)",parameters={"file_path":{"type":"str","description":"Model path"}})
    async def execute(self, **kw: Any) -> dict[str, Any]:
        try:
            import trimesh; mesh=trimesh.load(kw["file_path"])
            return {"status":"success","vertices":len(mesh.vertices),"faces":len(mesh.faces),"bounds":mesh.bounds.tolist(),"volume":float(mesh.volume) if mesh.is_watertight else None,"watertight":mesh.is_watertight}
        except ImportError: return {"status":"error","message":"pip install trimesh"}
        except Exception as e: return {"status":"error","message":str(e)}

class ThreeDAgent(BaseAgent):
    name = "threed"
    description = "3D model generation, scene building, format conversion, model analysis"
    tier = ModelTier.SPECIALIST
    system_prompt = "You are eVera's 3D Agent. Generate 3D models, build scenes, convert formats, analyze meshes."
    offline_responses = {"3d":"\U0001f4a0 3D modeling!","model":"\U0001f4a0 Creating model!","scene":"\U0001f3ac Building scene!","convert":"\U0001f504 Converting!"}
    def _setup_tools(self): self._tools = [Generate3DModelTool(),SceneBuilderTool(),ModelConverterTool(),ModelInfoTool()]
